### PR TITLE
Oindrila Ghosh (Portfolio)

### PR DESCRIPTION
**Pull request by Oindrila25**
My submission for the portfolio making hackathon

### CODE REVIEW

**Comment by loganrane** [comment]
Hey Oindrila, Congrats on making such a beautiful website. 🔥  Can you please move all your files inside a folder inside the "Portfolio-Websites" folder and commit again, so that it is organized and other people can share their websites as well. Thank you, do ask if you didn't get. As an example, you can go inside the "Portfolio-Websites" folder to see how to keep it.

Thank you! 👍

**Comment by Oindrila25** [comment]
Sure!

**Comment by Oindrila25** [comment]
I have put my files in a folder

**Comment by loganrane** [comment]
Awesome Job Oindrila. Thank you for your enthusiastic participation and congratulations on making your website.

**Review by loganrane — APPROVED** [review]

**Pull request merged**
