### PR TITLE
Tejas Tapas uploaded folder of my personal portfolio website website

### PR DESCRIPTION
**Pull request by Tejas1510**

### CODE REVIEW

**Comment by loganrane** [comment]
Tejas, it's great that you completed the website. We would love to review the code, can you please rename the folder to your name so that we can distinguish.

**Review by Tejas1510 — COMMENTED** [review]
Updated Readme

**Comment by Tejas1510** [comment]
Sir I don't know how to edit the folder name

**Comment by loganrane** [comment]
Change the folder name in your local machine and then commit, and make PR again and it'll be done

**Comment by Tejas1510** [comment]
Ok

**Comment by Tejas1510** [comment]
I have done that please have a check

**Review by loganrane — APPROVED** [review]

**Comment by loganrane** [comment]
Awesome Job Tejas!! Congratulations on making your portfolio website!

**Pull request merged**
