### PR TITLE
my portfolio website

### PR DESCRIPTION
**Pull request by raksha009**
Created portfolio website using CSS, HTML and a bit JS

### CODE REVIEW

**Comment by loganrane** [comment]
Raksha, Congrats on making your awesome website. Can you please add a README file and put the link of your hosted website in there. 
Thank you. 👍

**Comment by raksha009** [comment]
Thanks. Yaa sure

**Comment by raksha009** [comment]
Done

**Comment by loganrane** [comment]
Awesome job!!

**Pull request merged**
