### PR TITLE
added Gaurang Kamat's Portfolio

### PR DESCRIPTION
**Pull request by uchiha-saga2**

### CODE REVIEW

**Comment by ArpitFalcon** [comment]
Congratulations on making it on time, Gaurang!! Can you please send me the link to the hosted website? Do let me know if you are still having trouble in hosting it.

**Review by loganrane — COMMENTED** [review]
Congratulations on making it on time, Gaurang!! Can you please send me the link to the hosted website? Do let me know if you are still having trouble in hosting it.

**Review by loganrane — APPROVED** [review]
🔥

**Comment by uchiha-saga2** [comment]
Thank you so much Arpit for accepting my request. My website link is given below. Please free to give me any suggestions to improve in it. 

https://gauryker1969.github.io/

Regards,
Gaurang

**Pull request merged**
