### PR TITLE
Uploaded my portfolio

### PR DESCRIPTION
**Pull request by rakbarca10**

### CODE REVIEW

**Comment by loganrane** [comment]
Hi, Rakshit. Congratulations on making your own portfolio. 🔥  It would be great if you could host it on Github pages or Netlify and provide the hosted link along with a very short README file.  👍

**Comment by rakbarca10** [comment]
I have hosted it on Netlify
will provide the link

**Comment by rakbarca10** [comment]
https://rakportfolio.netlify.app/
Could you help me in adding it, I can't find my portfolio in  your
repository

**Comment by loganrane** [comment]
Rakshith, make a folder inside the "portfolio website" by your name and then commit. I'll include an example in there. See to it. :D

**Review by loganrane — APPROVED** [review]

**Pull request merged**
